

### Get Auth Token
### Remote Access User Token Call
# @name authRequest
POST https://aic-dev.authentication.us10.hana.ondemand.com/oauth/token
Accept: application/json;charset=utf8
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_id={{client-id}}
&client_secret={{client-secret}}
&response_type=token

###

@auth-token={{authRequest.response.body.access_token}}

### Post create person
post {{app_host}}/odata/v4/person/createPerson
Content-Type: application/json
Authorization: Bearer {{auth-token}}

{}
